### ISSUE TITLE
Formatting of results list in Windows is off

### ISSUE THREAD

**Issue by thesunshade** [simsapa/simsapa#3]
System: Windows 10

Problem: The heading of each result is cut off.

![image](https://user-images.githubusercontent.com/82448383/197132290-33032968-9f22-44c2-bdac-4fa3a01a803c.png)

I tried `view> Decrease text size` but that didn't change the text size of the results.

Perhaps somehow the line height is using an absolute value instead of a relative one?

**Comment by gambhiro** [comment]
What is your screen resolution?

Yes, they are fixed values, but the UI renders slightly differently on different platforms.

I think it will be best to provide a settings window to tweak the values for oneself.

Since you are running simsapa from source, you can experiment with the sizes to make it usable until then:

[layouts/search_item.py#L44](https://github.com/simsapa/simsapa/blob/main/simsapa/layouts/search_item.py#L44)

```
self.snippet.setStyleSheet("font-family: DejaVu Sans; font-size: 9pt;")

self.snippet.setMinimumHeight(25)
self.snippet.setMaximumHeight(60)
```

**Comment by gambhiro** [comment]
Try the Windows exe in the [v0.1.9-alpha.1](https://github.com/simsapa/simsapa/releases/tag/v0.1.9-alpha.1) release.

It is not an .msi installer, just run the .exe directly.

It includes a menu at View > Search Result Sizes to adjust.

If it works, you can remove your cloned source folder. To remove the installed libs from poetry, cd to simsapa and use `poetry env list` to show the name of the virtual env. Then `poetry env remove simsapa-...` will delete it. After that, you can delete the cloned simsapa folder and run it with the .exe instead.

**Comment by thesunshade** [comment]
Wonderful!

I ran the exe and without having to do any adjusting the search results look perfect. Thanks!
